#!/usr/bin/env python
# coding: utf-8

# # Question 3 : Part A

# In[5]:


lines = list()
with open('colours.tsv', 'r') as file:
    for line in file:
        lines.append(line.strip().split('\t'))
print(lines)


# # Question 3 : Part B

# In[6]:


colour_dic = dict()
for i in lines[:10]:
    col = i[1].split(',')
    colour_dic[i[0]] = {
        "red" : col[0], 
        "green": col[1],
        "blue" : col[2]
    }
print(colour_dic)


# Question 3 : Part C

# In[7]:


import json

with open('colour_dic.json', 'w') as file:
    json.dump(colour_dic, file)

